import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import { config } from '../config.js';
import { AuthError } from './auth.js';

/**
 * Uploaded profile pictures.
 *
 * Trusting the browser's Content-Type would let anyone store an HTML or SVG
 * file that later executes in a viewer's origin, so the format is decided by
 * the file's own magic bytes and nothing else. SVG is deliberately not on the
 * list: it can carry script. Files are written under a random name — never one
 * derived from user input — and served back with a fixed Content-Type and
 * `nosniff`, so what goes in is exactly what comes out.
 */

const SIGNATURES: { ext: string; mime: string; test: (buffer: Buffer) => boolean }[] = [
  {
    ext: 'png',
    mime: 'image/png',
    test: (b) => b.length > 8 && b.subarray(0, 8).toString('hex') === '89504e470d0a1a0a',
  },
  {
    ext: 'jpg',
    mime: 'image/jpeg',
    test: (b) => b.length > 3 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff,
  },
  {
    ext: 'gif',
    mime: 'image/gif',
    test: (b) => b.length > 6 && (b.subarray(0, 6).toString('ascii') === 'GIF87a' || b.subarray(0, 6).toString('ascii') === 'GIF89a'),
  },
  {
    ext: 'webp',
    mime: 'image/webp',
    test: (b) =>
      b.length > 12 &&
      b.subarray(0, 4).toString('ascii') === 'RIFF' &&
      b.subarray(8, 12).toString('ascii') === 'WEBP',
  },
];

export interface StoredAvatar {
  /** Same-origin path stored on the account, e.g. /api/avatar/ab12….gif */
  url: string;
  file: string;
  mime: string;
  bytes: number;
}

export function detectImage(buffer: Buffer): { ext: string; mime: string } | null {
  return SIGNATURES.find((signature) => signature.test(buffer)) ?? null;
}

/** Writes the upload to disk and returns the path to store on the account. */
export async function storeAvatar(buffer: Buffer): Promise<StoredAvatar> {
  if (buffer.length === 0) throw new AuthError('That file is empty.', 400, 'invalid_image');
  if (buffer.length > config.avatarMaxBytes) {
    throw new AuthError(
      `Profile pictures must be under ${Math.round(config.avatarMaxBytes / 1024 / 1024)} MB.`,
      413,
      'image_too_large',
    );
  }

  const kind = detectImage(buffer);
  if (!kind) {
    throw new AuthError(
      'That file is not a PNG, JPEG, GIF or WebP image.',
      400,
      'invalid_image',
    );
  }

  await fs.mkdir(config.avatarDir, { recursive: true });
  const file = `${crypto.randomBytes(16).toString('hex')}.${kind.ext}`;
  const target = path.join(config.avatarDir, file);

  // Written to a temp name first so a half-flushed file is never served.
  const temp = `${target}.tmp`;
  await fs.writeFile(temp, buffer);
  await fs.rename(temp, target);

  return { url: `/api/avatar/${file}`, file, mime: kind.mime, bytes: buffer.length };
}

/** Resolves a stored avatar path to a file on disk, or null if it isn't one. */
export function resolveAvatarFile(fileName: string): { path: string; mime: string } | null {
  // The name is generated by storeAvatar, so anything that doesn't match that
  // exact shape is not ours — and can't be a traversal attempt either.
  const match = /^([a-f0-9]{32})\.(png|jpg|jpeg|gif|webp)$/.exec(fileName);
  if (!match) return null;

  const ext = match[2] === 'jpeg' ? 'jpg' : match[2]!;
  const mime = SIGNATURES.find((signature) => signature.ext === ext)?.mime;
  if (!mime) return null;

  return { path: path.join(config.avatarDir, fileName), mime };
}

/** Deletes a previously uploaded avatar; ignores anything not stored here. */
export async function deleteAvatarFile(url: string | null): Promise<void> {
  if (!url) return;
  const fileName = url.startsWith('/api/avatar/') ? url.slice('/api/avatar/'.length) : null;
  if (!fileName) return;
  const resolved = resolveAvatarFile(fileName);
  if (!resolved) return;
  await fs.rm(resolved.path, { force: true });
}
